"""Vault-facing outputs: the MCP Directory note, a usage report, and tasks.

Everything written here is either inside a generated marker block or an
append — existing prose is never rewritten, per the vault's mutability
conventions.
"""

import datetime
import re
from pathlib import Path

from .common import (REGISTRY_PATH, TASKS_INBOX, WEEKLY_NOTE, fmt_mb,
                     fmt_tokens, load_json, save_json)

NOTE_BEGIN = "<!-- mcp-dashboard:begin (generated - edits inside this block are overwritten) -->"
NOTE_END = "<!-- mcp-dashboard:end -->"
TASK_MARKER = "mcp-dashboard"


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

def update_registry(servers, now_iso):
    registry = load_json(REGISTRY_PATH) or {}
    entries = registry.get("servers", {})
    for s in servers:
        e = entries.get(s["key"], {})
        e.update({
            "name": s["name"], "agent": s["agent"], "scope": s["scope"],
            "origin": s["origin"], "transport": s["transport"],
            "command": s["command"], "provenance": s.get("provenance", "unknown"),
            "last_seen": now_iso, "last_status": s.get("status", "unknown"),
            "last_ram_mb": round(s.get("ram_bytes", 0) / 1048576, 1),
            "calls_30d": s.get("calls_30d", 0), "calls": s.get("calls", 0),
            "last_used": s.get("last_used"), "verdict": s.get("verdict", ""),
            "tools": s.get("tools_count", 0), "ctx_tokens": s.get("ctx_tokens", 0),
            "enabled": s.get("enabled", True),
        })
        e.setdefault("first_seen", now_iso)
        e["peak_ram_mb"] = max(e.get("peak_ram_mb", 0), e["last_ram_mb"])
        entries[s["key"]] = e
    registry["servers"] = entries
    registry["last_scan"] = now_iso
    save_json(REGISTRY_PATH, registry)
    return registry


# ---------------------------------------------------------------------------
# MCP Directory note
# ---------------------------------------------------------------------------

def render_note_block(registry, servers, now_iso):
    entries = sorted(registry.get("servers", {}).values(),
                     key=lambda e: (-e.get("last_ram_mb", 0), e["name"]))
    today = now_iso[:10]
    live_keys = {s["key"] for s in servers}
    lines = [
        NOTE_BEGIN,
        f"_Last scan: {registry.get('last_scan', now_iso)}_",
        "",
        "| Server | Agent | Scope | Provenance | Status | Verdict | Calls 30d | Last used | RAM | Peak | Context | First seen |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for e in entries:
        gone = e.get("last_seen", "")[:10] != today
        name = f"~~{e['name']}~~" if gone else f"**{e['name']}**"
        status = "removed from config" if gone else e.get("last_status", "unknown")
        last_used = (e.get("last_used") or "")[:10] or "never"
        lines.append(
            f"| {name} | {e.get('agent', 'claude')} | {e['scope']} "
            f"| {e.get('provenance', 'unknown')} | {status} | {e.get('verdict', '')} "
            f"| {e.get('calls_30d', 0)} | {last_used} "
            f"| {e.get('last_ram_mb', 0):g} MB | {e.get('peak_ram_mb', 0):g} MB "
            f"| {fmt_tokens(e.get('ctx_tokens', 0))} | {e.get('first_seen', '')[:10]} |")
    if not entries:
        lines.append("| _none seen yet_ | | | | | | | | | | | |")
    lines.append(NOTE_END)
    return "\n".join(lines)


DIRECTORY_TEMPLATE = """---
mutability: living
type: dashboard
tags: [mcp, tooling, dashboard]
---

# MCP Directory

Persistent registry of every MCP server this machine has ever had in its
toolbox — Claude Code, Codex, Gemini, and Cursor, current and past.
Generated by `Obsidian Vault Management/Scripts/MCP Dashboard/mcp_dashboard.py`.

Design and build record: [[MCP Server Management]].
Visual dashboard: `MCP Server Dashboard.html` in this folder.

{block}

## Notes

- stdio servers spawn one process tree **per open agent session** — the usual
  cause of MCP RAM drain.
- Label your own servers in `mcp-provenance.json` next to the script.
- Verdicts come from cost weighed against recorded use: `earning`, `quiet`,
  `dormant`, `unused`, `expensive`, `broken`, `disabled`.
"""


def write_directory_note(path, registry, servers, now_iso):
    block = render_note_block(registry, servers, now_iso)
    path = Path(path)
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if NOTE_BEGIN in text and NOTE_END in text:
            pre = text.split(NOTE_BEGIN)[0]
            post = text.split(NOTE_END, 1)[1]
            path.write_text(pre + block + post, encoding="utf-8")
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(DIRECTORY_TEMPLATE.format(block=block), encoding="utf-8")


# ---------------------------------------------------------------------------
# Usage report
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = """---
mutability: living
type: report
tags: [mcp, tooling, report]
---

# MCP Usage Report

Rolling record of what the MCP toolbox costs and what it earns. Appended by
`mcp_dashboard.py --report`; newest entry first. Method and design:
[[MCP Server Management]].

"""


def append_report(servers, recs, totals_d, now_iso, path=None):
    """Prepend a dated snapshot to the usage report note."""
    path = Path(path or WEEKLY_NOTE)
    ranked = sorted(servers, key=lambda s: -s.get("calls_30d", 0))
    used = [s for s in ranked if s.get("calls_30d", 0) > 0][:5]
    idle = [s for s in ranked if s.get("calls_30d", 0) == 0
            and s.get("ram_bytes", 0) > 0][:5]
    lines = [f"## {now_iso[:10]}", ""]
    lines.append(
        f"- Local RAM: **{fmt_mb(totals_d['ram'])}** across "
        f"{sum(1 for s in servers if s.get('instances'))} running server(s); "
        f"context cost ~{fmt_tokens(totals_d['tokens'])} tokens "
        f"({totals_d['tools']} tools); {totals_d['calls30']} calls in 30 days.")
    if totals_d["reclaimable"]:
        lines.append(f"- Reclaimable by switching off unused servers: "
                     f"**{fmt_mb(totals_d['reclaimable'])}**.")
    if used:
        lines.append("- Most used: " + ", ".join(
            f"{s['name']} ({s['calls_30d']})" for s in used) + ".")
    if idle:
        lines.append("- Costing without calls: " + ", ".join(
            f"{s['name']} ({fmt_mb(s.get('ram_bytes', 0))})" for s in idle) + ".")
    for r in recs[:5]:
        lines.append(f"    - {r['severity']}: {r['title']} — {r['detail']}")
    lines.append("")
    entry = "\n".join(lines)

    if path.exists():
        text = path.read_text(encoding="utf-8")
        if f"\n## {now_iso[:10]}\n" in text:  # replace today's entry
            text = re.sub(r"(?ms)^## " + re.escape(now_iso[:10]) + r"\n.*?(?=^## |\Z)",
                          entry, text)
            path.write_text(text, encoding="utf-8")
            return path
        marker = "[[MCP Server Management]].\n\n"
        if marker in text:
            head, tail = text.split(marker, 1)
            path.write_text(head + marker + entry + tail, encoding="utf-8")
        else:
            path.write_text(text.rstrip() + "\n\n" + entry, encoding="utf-8")
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(REPORT_TEMPLATE + entry, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Tasks
# ---------------------------------------------------------------------------

def append_tasks(recs, now_iso, path=None, limit=5):
    """Append high-severity findings to the task inbox, skipping any whose
    title is already present. Returns the list of task lines written."""
    path = Path(path or TASKS_INBOX)
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    wanted = [r for r in recs if r["severity"] == "high"][:limit]
    new = []
    for r in wanted:
        if r["title"] in text:
            continue
        action = {"disable": "Switch off", "secret": "Move to an env var",
                  "review": "Review"}.get(r["action"], "Review")
        new.append(f"- [ ] {action}: {r['title']} — {r['detail']} "
                   f"[area:: tooling] #task #inbox [source:: {TASK_MARKER}]")
    if not new:
        return []
    section = (f"\n## MCP toolbox hygiene — {now_iso[:10]}\n\n"
               f"Source: [[MCP Directory]] · generated by "
               f"`mcp_dashboard.py --tasks`\n\n" + "\n".join(new) + "\n")
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(section)
    return new
